on: 
  release:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Dataverse Uploader Action 
        uses: IQSS/dataverse-uploader@v1.1
        with:
          DATAVERSE_TOKEN: ${{secrets.DATAVERSE_TOKEN}}
          DATAVERSE_SERVER: https://dataverse.harvard.edu/
          DATAVERSE_DATASET_DOI: doi:10.7910/DVN/1JFUWF